authorizedkeys:
  autodestroy: always
  deployment_strategy: every_node
  environment:
    - AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDD6CvzGG8FOEsvzsYIws3LXNLl3ozwnQ17HQHGMvIoQgFTjzak2HnM9eknbP+LkRMgikuCNbTpZNYQIwmnlQ31XDye0bIdRHoFdF+cKpF/zt1G5IK+kRT/Cvgd1PxDLj5QcoietpS93iBa0r/ghqv48NLLJZQxQYw5OhRRq9Id/A6AHKTCFBTgeHbB5CoLwD8LVJkXEmJjIv8M2bxMt9xmRgArR9BH9rGRFQaI0r6Dr1bWSNm2ayOYgjAkVVkDjTs0w6bo1AbQztdPqVQrJSLQl/WQuqOQBzZe+0ExYa67Y93TNmYfuztYpZ4gr24mvkNATNDyEW0IfwIgjh9xFiaVY/K+PyoXGbKyjsEcddFuj7xt+23VkrCfPV29dor9Af/WnDETSaRrxlCn2c009eqfP9bkzR+1b61Lw9pN2RFSaU9TsAzBfPKJPVtiBCNrdN93fMAJLZaV8v+skpMdE7FT2GRmax52hp+YmopT+I/IcDh6gs6fBWntIGPpEIS4ysWF9mUa1uGF3gh7DovO88+u+rHDmW6K3O14/ExRjjVlKB+VkU8y9weXu2SsthkYv9/c2u81oVFy8rrMKffeF98K1SnBuGRSdRcjC/9uLBxJh3n3HSIVw0+Etqv9RCaM9teDiRsPmmsvAfrU3FZA8uO12wwdP77hGyiqAdSzs/RPpQ== l@lucasvo.com
  image: 'dockercloud/authorizedkeys:latest'
  volumes:
    - '/root:/user'
ioverlander:
  autoredeploy: true
  command: run
  environment:
    - ASSETS_OUTPUT_PATH=/assets/
    - BUILD_ASSETS_ON_LAUNCH=1
    - DB_HOSTNAME=postgres
    - DB_PASSWORD=password
    - DB_USERNAME=user
    - NODE_ENV=staging
  expose:
    - '3000'
  image: 'ioverlanderapp/ioverlander-server:latest'
  links:
    - postgres
  target_num_containers: 2
  volumes:
    - '/data/assets:/assets'
postgres:
  environment:
    - PGDATA=/pgdata
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=user
  image: 'postgres:9.6'
  volumes:
    - '/data/pgdata:/var/lib/postgresql/data'
staticassets:
  image: 'nginx:latest'
  ports:
    - '80:3001'
  volumes:
    - '/data/assets:/usr/share/nginx/html'


